### PR TITLE
Fix infinite loop in useEffect

### PR DESCRIPTION
**Pull request by lukebennett88**
This PR addresses the following issue:
https://github.com/thetrevorharmon/sell-things-fast/issues/2

### CODE REVIEW

**Comment by thetrevorharmon** [comment]
Thanks for this @lukebennett88. I deployed a preview of this to Netlify, will you look at it and make sure that the error is fixed? (seems like it on my end, it would be good to get your eyes on it 👀)

**Comment by lukebennett88** [comment]
Hi Trevor,

Thanks for taking a look — and thanks for putting this repo together, I learnt a lot from digging through the code 😊

Credit goes to @nandorojo for coming up with a much nicer way to fix the issue than I did.

Here is a screenshot of the GraphQL requests on the current live version of the site:
sell-things-fast

And here is a screenshot of the GraphQL requests on the deploy preview:
 
sell-things-fast-deploy-preview

I'm only seeing the one request, so looks like everything is working correctly 🎉

**Comment by thetrevorharmon** [comment]
@lukebennett88 awesome! Thank you!

**Comment by nandorojo** [comment]
Glad to see the fix!

**Pull request merged**
